### ISSUE TITLE
Create User for jenkins

### ISSUE THREAD

**Issue by donovosoft** [donovosoft/ansible-scripts#6]
Create user in jenkins role with name jobbuilder and update the password in jenkins-job-builder ini

**Comment by maubarrerag** [comment]
It is not recommended  the use of internal db for jenkins, it can be done with ldap or another dbms (mysql,postgresql,etc..)

this issue can be close

**Comment by donovosoft** [comment]
Ok, we should figure out how to do it, i prefer to do it with ldap
