### ISSUE TITLE
Make developement branch as default branch

### ISSUE THREAD

**Issue by donovosoft** [donovosoft/ansible-scripts#9]
Change the default branch for "development" and protect master branch. Delete all unused branches except for development and master and close/merge any pending Pull request.

@maubarrerag

**Comment by maubarrerag** [comment]
Only branch Issue #6 is pending for review i will complete the work in there and create a new pr.

**Comment by maubarrerag** [comment]
Done

**Comment by donovosoft** [comment]
Thanks
